package impulsestorm.liftapp.model

import impulsestorm.liftapp.lib._

import scala.util.Random

case class Star( id: Int, name: String, sClass: StarClass.Value, 
                 x: Double, y: Double, planets: List[Planet])
                 
object Star {
  
  import StarClass._
  
  def getRandom( mapSizeL: Double, id: Int, sName: String ) = {
    val sClass = SimRandom.weightedRandom(StarClass.abundances)
    
    Star(id=id, name=sName, sClass=sClass,
         x=Random.nextDouble*mapSizeL, y=Random.nextDouble*mapSizeL,
         planets = randomPlanets(sClass))
  }
  
  def randomPlanets( sClass: StarClass.Value ) : List[Planet] = {
    val nPlanets = StarClass.randomNPlanets(sClass)
    
    val zones = 
      List.fill(nPlanets)(StarClass.randomZone(sClass, nPlanets)).sorted
    
    val idZonePairs = (1 to nPlanets).toList zip zones 
    
    idZonePairs.map(p => Planet.genRandom(p._1, sClass, p._2))
  }
 
  val names = List(
    "Acamar", 
    "Achernar", 
    "Acrux", 
    "Acubens", 
    "Adhafera", 
    "Adhara", 
    "Agena", 
    "Albali", 
    "Albireo", 
    "Alchiba", 
    "Alcor", 
    "Alcyone", 
    "Aldebaran", 
    "Alderamin", 
    "Alfirk", 
    "Algedi",
    "Algenib", 
    "Algieba", 
    "Algol", 
    "Algorab", 
    "Alhena", 
    "Alioth", 
    "Alkaid", 
    "Alkalurops", 
    "Alkes", 
    "Almach", 
    "Al Na'ir", 
    "Alnasl", 
    "Alnilam", 
    "Alnitak", 
    "Al Niyat", 
    "Alphard", 
    "Alphecca", 
    "Alpheratz", 
    "Alrescha", 
    "Alshain", 
    "Altair", 
    "Altais", 
    "Alterf", 
    "Aludra", 
    "Alula Australis", 
    "Alula Borealis", 
    "Alya", 
    "Ancha", 
    "Ankaa", 
    "Antares", 
    "Arcturus", 
    "Arkab", 
    "Arneb", 
    "Ascella", 
    "Asellus Australis", 
    "Asellus Borealis", 
    "Aspidiske", 
    "Asterope", 
    "Atik", 
    "Atlas", 
    "Atria", 
    "Avior", 
    "Azha", 
    "Baten Kaitos", 
    "Becrux", 
    "Beid", 
    "Bellatrix", 
    "Benetnasch", 
    "Betelgeuse", 
    "Biham", 
    "Canopus", 
    "Capella", 
    "Caph", 
    "Castor", 
    "Cebalrai", 
    "Celaeno", 
    "Chara", 
    "Cheleb", 
    "Chertan", 
    "Chort", 
    "Cor Caroli", 
    "Cursa", 
    "Dabih", 
    "Deneb", 
    "Deneb Algedi", 
    "Deneb Kaitos", 
    "Denebola", 
    "Diphda", 
    "Dnoces", 
    "Talitha", 
    "Dschubba", 
    "Dubhe", 
    "Edasich", 
    "Electra", 
    "Elnath", 
    "Eltanin", 
    "Enif", 
    "Errai", 
    "Fomalhaut", 
    "Furud", 
    "Gacrux", 
    "Garnet Star", 
    "Gemma", 
    "Giausar", 
    "Gienah", 
    "Gienah", 
    "Girtab", 
    "Gomeisa", 
    "Graffias", 
    "Grumium", 
    "Hadar", 
    "Hamal", 
    "Homam", 
    "Izar", 
    "Kaus Australis", 
    "Kaus Borealis", 
    "Kaus Media", 
    "Kaus Meridianalis", 
    "Keid", 
    "Kitalpha", 
    "Kochab", 
    "Kornephoros", 
    "Lesath", 
    "Maia", 
    "Marfik", 
    "Markab", 
    "Matar", 
    "Mebsuta", 
    "Media", 
    "Megrez", 
    "Meissa", 
    "Mekbuda", 
    "Menkab", 
    "Menkalinan", 
    "Menkar", 
    "Menkent", 
    "Merak", 
    "Merope", 
    "Mesarthim", 
    "Miaplacidus", 
    "Mimosa", 
    "Mintaka", 
    "Mira", 
    "Mirach", 
    "Mirfak", 
    "Mirzam", 
    "Mizar", 
    "Mothallah", 
    "Muhlifain", 
    "Muliphen", 
    "Muphrid", 
    "Muscida", 
    "Naos", 
    "Nashira", 
    "Navi", 
    "Nekkar", 
    "Nihal", 
    "Nunki", 
    "Nusakan", 
    "Peacock", 
    "Phact", 
    "Phad", 
    "Phecda", 
    "Pherkad", 
    "Pleione", 
    "Polaris", 
    "Pollux", 
    "Porrima", 
    "Procyon", 
    "Propus", 
    "Pulcherrima", 
    "Rasalgethi", 
    "Rasalhague", 
    "Ras Elased", 
    "Rastaban", 
    "Regor", 
    "Regulus", 
    "Rigel", 
    "Rigil Kent", 
    "Rigil Kentaurus", 
    "Rotanev", 
    "Ruchba", 
    "Ruchbah", 
    "Rukbat", 
    "Runaway Star", 
    "Sabik", 
    "Sadalachbia", 
    "Sadalbari", 
    "Sadalmelik", 
    "Sadalsuud", 
    "Sadatoni", 
    "Sadr", 
    "Saiph", 
    "Sargas", 
    "Scheat", 
    "Schedar", 
    "Seginus", 
    "Shaula", 
    "Sheliak", 
    "Sheratan", 
    "Sirius", 
    "Situla", 
    "Skat", 
    "Spica", 
    "Sterope I", 
    "Sterope II", 
    "Sualocin", 
    "Suhail", 
    "Sulafat", 
    "Syrma", 
    "Talitha", 
    "Tania Australis", 
    "Tania Borealis", 
    "Tarazed", 
    "Taygeta", 
    "Tegmine", 
    "Thuban", 
    "Unukalhai", 
    "Vega", 
    "Vindemiatrix", 
    "Wasat", 
    "Wazn", 
    "Wezen", 
    "Yed Posterior", 
    "Yed Prior", 
    "Yildun", 
    "Zaniah", 
    "Zaurak", 
    "Zavijava", 
    "Zosma", 
    "Zubenelgenubi", 
    "Zubeneschamali"
  )
    
  
}


